import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createState,updateState,updateFrame,interact,trailX,objectives} from '../src/game.js';
test('driving consumes fuel and brakes reduce speed',()=>{const s=createState();for(let i=0;i<100;i++)updateState(s,{w:true},.05);assert.ok(s.z>0);assert.ok(s.fuel<100);const before=s.speed;updateState(s,{brake:true},.05);assert.ok(s.speed<before);});
test('water requires proximity and a stopped vehicle and cannot be collected twice',()=>{const s=createState();assert.equal(interact(s).won,undefined);s.z=360;s.x=trailX(s.z);s.speed=5;interact(s);assert.equal(s.completed.length,0);s.speed=0;interact(s);assert.equal(s.water,84);interact(s);assert.equal(s.water,84);});
test('camp requires every prior objective and completes expedition',()=>{const s=createState();s.z=1470;s.x=trailX(s.z);interact(s);assert.equal(s.won,false);s.completed=[0,1,2,3];assert.equal(interact(s).won,true);assert.equal(s.completed.length,objectives.length);});
test('low range protects suspension while fast offroad driving damages it',()=>{const s=createState();s.x=40;s.speed=15;updateState(s,{},.05);assert.ok(s.health<100);s.health=100;s.low=true;updateState(s,{},.05);assert.equal(s.health,100);});
test('resource exhaustion stops driving',()=>{const s=createState();s.fuel=.001;s.speed=12;updateState(s,{w:true},.05);assert.equal(s.failed,true);assert.equal(s.speed,0);});

test("slow render frames advance the same simulation time as fast frames",()=>{const slow=createState(),fast=createState();for(let i=0;i<20;i++)updateFrame(slow,{w:true},.25);for(let i=0;i<100;i++)updateFrame(fast,{w:true},.05);assert.ok(Math.abs(slow.z-fast.z)<1e-8);assert.ok(slow.z>20);assert.ok(Math.abs(slow.elapsed-5)<1e-8);});

test('steering changes heading and movement follows the vehicle direction',()=>{const s=createState();s.speed=8;const heading=s.heading,x=s.x;for(let i=0;i<10;i++)updateState(s,{d:true,w:true},.05);assert.ok(s.heading>heading);assert.ok(s.x>x);assert.ok(s.steering>0);});
test('wheels rotate from distance and reverse rotates them backwards',()=>{const s=createState();s.z=200;s.x=trailX(200);s.heading=0;s.speed=4;updateState(s,{},.05);assert.ok(s.wheelAngle>0);const angle=s.wheelAngle;s.speed=-4;updateState(s,{},.05);assert.ok(s.wheelAngle<angle);});
test('reverse input brakes forward motion before engaging reverse',()=>{const s=createState();s.speed=8;updateState(s,{s:true},.05);assert.ok(s.speed>0&&s.speed<8);for(let i=0;i<50;i++)updateState(s,{s:true},.05);assert.ok(s.speed<0);});
test('braking holds the vehicle without accelerating',()=>{const s=createState();for(let i=0;i<40;i++)updateState(s,{w:true,brake:true},.05);assert.equal(s.speed,0);assert.equal(s.wheelAngle,0);});
test('reverse steering changes heading opposite to forward steering',()=>{const s=createState();s.z=200;s.x=trailX(200);s.heading=0;s.speed=-5;for(let i=0;i<10;i++)updateState(s,{d:true},.05);assert.ok(s.heading<0);});

import {recover,restoreState} from '../src/game.js';
import {obstacles,surfaceAt,alternateX,surfaceHeight} from '../src/terrain.js';
test('solid obstacles stop travel and cause speed-dependent damage',()=>{const o=obstacles.find(o=>o.type==='rock'),s=createState();s.z=o.z;s.x=o.x;s.speed=10;updateState(s,{},.05);assert.ok(Math.hypot(s.x-o.x,s.z-o.z)>=o.radius+1.049);assert.ok(s.health<100);assert.ok(Math.abs(s.speed)<2);});
test('low range and locker improve acceleration on loose ground',()=>{const normal=createState(),locked=createState();for(const s of [normal,locked]){s.z=600;s.x=trailX(600);s.heading=0;}locked.low=true;locked.locked=true;updateState(normal,{w:true},.05);updateState(locked,{w:true},.05);assert.ok(locked.speed>normal.speed);assert.equal(surfaceAt(trailX(600),600).name,'LOOSE ROCK');});
test('hill-climb detour rejoins trail and has a raised driving surface',()=>{assert.equal(alternateX(500),trailX(500));assert.ok(Math.abs(alternateX(780)-trailX(780))<1e-8);assert.ok(surfaceHeight(alternateX(640),640)>surfaceHeight(trailX(640),640));});
test('recovery requires stopping, returns to last safe position and uses a finite kit',()=>{const s=createState();s.lastSafe={x:4,z:20};s.speed=5;recover(s);assert.equal(s.recoveries,2);s.speed=0;recover(s);assert.equal(s.x,4);assert.equal(s.z,20);assert.equal(s.recoveries,1);recover(s);recover(s);assert.equal(s.recoveries,0);});
test('saved expedition resumes safely and rejects damaged or incompatible saves',()=>{const s=createState();s.z=360;s.x=trailX(360);s.completed=[0,1];s.speed=15;const value={version:2,state:s};const restored=restoreState(value);assert.equal(restored.speed,0);assert.deepEqual(restored.completed,[0,1]);assert.equal(restoreState({...value,version:1}),null);assert.equal(restoreState({version:2,state:{...s,fuel:Infinity}}),null);assert.equal(restoreState({version:2,state:{...s,completed:[5]}}),null);});
test('uphill driving loses more speed than downhill driving',()=>{const up=createState(),down=createState();for(const s of [up,down]){s.z=10;s.x=trailX(10);s.speed=6;}up.heading=0;down.heading=Math.PI;updateState(up,{},.05);updateState(down,{},.05);assert.ok(up.speed<down.speed);});
