import * as THREE from 'three';
import './style.css';
import {RoundedBoxGeometry} from 'three/addons/geometries/RoundedBoxGeometry.js';
import {surfaceHeight,enhanceWorld} from './graphics.js';
import {trailX,trailHeight,TRAIL_LENGTH,objectives,createState,updateFrame,interact} from './game.js';
const $=id=>document.getElementById(id);
const scene=new THREE.Scene(); scene.background=new THREE.Color('#d5a078'); scene.fog=new THREE.FogExp2('#b59889',.0006);
const renderer=new THREE.WebGLRenderer({canvas:$('world'),antialias:true}); renderer.setPixelRatio(Math.min(devicePixelRatio,2)); renderer.shadowMap.enabled=true; renderer.shadowMap.type=THREE.PCFSoftShadowMap; renderer.outputColorSpace=THREE.SRGBColorSpace; renderer.toneMapping=THREE.ACESFilmicToneMapping; renderer.toneMappingExposure=1.15;
const camera=new THREE.PerspectiveCamera(52,innerWidth/innerHeight,.1,2600);
scene.add(new THREE.HemisphereLight('#c0cddd','#8a755b',2.15));scene.add(new THREE.AmbientLight('#c8b99d',.35));
const sun=new THREE.DirectionalLight('#ffbc72',3.6);sun.position.set(-180,180,-400);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-90;sun.shadow.camera.right=90;sun.shadow.camera.top=90;sun.shadow.camera.bottom=-90;sun.shadow.camera.far=600;sun.shadow.bias=-.001;scene.add(sun);scene.add(sun.target);
const mat=(c,r=1)=>new THREE.MeshStandardMaterial({color:c,roughness:r});
const sand=mat('#b78050'),rockMats=['#a16842','#995e3d','#b98152','#835540'].map(c=>mat(c)),greenMats=['#424b2a','#59603b','#6a6840'].map(c=>mat(c)),black=mat('#202621'),body=mat('#c8b88e',.55),glass=new THREE.MeshStandardMaterial({color:'#1e3439',roughness:.2,metalness:.5}),chrome=mat('#525b54',.4),red=mat('#ab3027'),amber=new THREE.MeshStandardMaterial({color:'#ffbc52',emissive:'#ff9019',emissiveIntensity:.8});
function mesh(geometry,material,x,y,z,parent=scene){const m=new THREE.Mesh(geometry,material);m.position.set(x,y,z);parent.add(m);return m;}
function box(w,h,d,m,x,y,z,p){const o=mesh(new RoundedBoxGeometry(w,h,d,2,Math.min(w,h,d)*.18),m,x,y,z,p);o.castShadow=true;o.receiveShadow=true;return o;}
let seed=97;function rand(){seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;}
// Terrain uses a continuous trail surface; shoulders rise into the canyon.
const geo=new THREE.PlaneGeometry(900,2100,220,420);geo.rotateX(-Math.PI/2);const pos=geo.attributes.position;const colors=[];
for(let i=0;i<pos.count;i++){const x=pos.getX(i),z=800-pos.getZ(i);pos.setZ(i,-z);const dist=Math.abs(x-trailX(z));const shoulder=Math.max(0,dist-11);const noise=Math.sin(x*.16+z*.12)*Math.cos(z*.18)*Math.min(1.5,shoulder*.12);pos.setY(i,surfaceHeight(x,z));const c=new THREE.Color(dist<10?'#b89063':dist<15?'#a47b50':'#94663f');c.multiplyScalar(.87+rand()*.22);colors.push(c.r,c.g,c.b);}geo.setAttribute('color',new THREE.Float32BufferAttribute(colors,3));geo.computeVertexNormals();const ground=mesh(geo,new THREE.MeshStandardMaterial({vertexColors:true,roughness:1}),0,0,0);ground.receiveShadow=true;
// Distant mesas and sculpted rock formations.
for(let i=0;i<100;i++){const z=rand()*2050-200;const side=rand()>.5?1:-1;const x=trailX(z)+side*(230+rand()*300);const h=20+rand()*65;const g=new THREE.CylinderGeometry(15+rand()*30,30+rand()*42,h,5+Math.floor(rand()*3));const gp=g.attributes.position;for(let v=0;v<gp.count;v++){const px=gp.getX(v),py=gp.getY(v),pz=gp.getZ(v);const ripple=1+Math.sin(py*.45+px*.09)*.05+Math.sin(pz*.3)*.07;gp.setXYZ(v,px*ripple,py,pz*ripple);}g.computeVertexNormals();const o=mesh(g,rockMats[i%4],x,trailHeight(z)+h*.4,-z);o.rotation.y=rand()*6; o.scale.z=.6+rand();o.castShadow=true;}
for(let i=0;i<500;i++){const z=rand()*1750-100;const x=trailX(z)+(rand()>.5?1:-1)*(15+rand()*50);const y=surfaceHeight(x,z);if(i%4===0){const r=mesh(new THREE.DodecahedronGeometry(.5+rand()*3,1),rockMats[i%4],x,y,-z);r.scale.set(1.5,.8,1);r.rotation.set(rand(),rand()*6,rand());r.castShadow=true;}}
// River glints far below the eastern cliffs.
const river=mesh(new THREE.PlaneGeometry(85,2000),new THREE.MeshStandardMaterial({color:'#688d92',roughness:.23,metalness:.3}),190,-4,-700);river.rotation.x=-Math.PI/2;

// Stylized fifth-generation Toyota 4Runner with roof rack, supplies, spare tire and off-road tires.
const car=new THREE.Group();scene.add(car);
box(2.25,.73,4.4,body,0,1.03,0,car);box(2.08,.15,4.25,black,0,.61,0,car);box(2.05,.67,2.8,body,0,1.7,.27,car);box(2.12,.13,2.92,body,0,2.08,.27,car);
box(1.84,.5,.04,glass,0,1.76,-1.16,car);box(1.85,.5,.04,glass,0,1.76,1.69,car);
for(const side of [-1,1]){for(const z of [-.62,.35,1.12])box(.035,.49,.7,glass,side*1.044,1.76,z,car);box(.18,.12,.3,black,side*1.2,1.48,-1.1,car);box(.12,.1,3.2,black,side*1.17,.66,.1,car);for(const z of [-1.38,1.42]){box(.18,.5,.94,black,side*1.13,.87,z,car);const tire=mesh(new THREE.CylinderGeometry(.55,.55,.35,14),black,side*1.13,.55,z,car);tire.rotation.z=Math.PI/2;tire.castShadow=true;const rim=mesh(new THREE.CylinderGeometry(.29,.29,.37,8),chrome,side*1.14,.55,z,car);rim.rotation.z=Math.PI/2;}}
box(2.3,.22,.24,black,0,.82,-2.23,car);box(2.3,.2,.24,black,0,.82,2.24,car);box(1,.34,.06,black,0,1.15,-2.22,car);
for(const s of [-1,1]){box(.5,.23,.08,amber,s*.79,1.2,-2.22,car);box(.31,.38,.09,red,s*.96,1.13,2.23,car);box(.32,.1,.1,amber,s*.96,1.2,2.24,car);}
box(1.9,.13,2.5,black,0,2.23,.2,car);for(const s of [-1,1])box(.08,.17,2.7,chrome,s*.96,2.36,.2,car);for(const z of [-1.1,-.4,.4,1.5])box(1.99,.12,.08,chrome,0,2.35,z,car);
box(1.3,.38,1.2,mat('#7d805b'),-.2,2.49,.4,car);box(.63,.3,.65,mat('#b6a379'),.47,2.48,-.66,car);box(.7,.4,.45,mat('#a78657'),-.46,2.5,-.68,car);for(const x of [-.6,.4])box(.04,.41,1.21,black,x,2.52,.4,car);
const spare=mesh(new THREE.CylinderGeometry(.59,.59,.32,14),black,.34,1.27,2.47,car);spare.rotation.x=Math.PI/2;const spareRim=mesh(new THREE.CylinderGeometry(.3,.3,.34,8),chrome,.34,1.27,2.48,car);spareRim.rotation.x=Math.PI/2;box(.42,.6,.25,mat('#8c8356'),-.73,1.2,2.41,car);
// Rear Toyota lettering as a canvas texture.
const badgeCanvas=document.createElement('canvas');badgeCanvas.width=256;badgeCanvas.height=64;const bc=badgeCanvas.getContext('2d');bc.fillStyle='#dad9bb';bc.font='bold 30px sans-serif';bc.textAlign='center';bc.fillText('TOYOTA',128,40);mesh(new THREE.PlaneGeometry(.6,.15),new THREE.MeshBasicMaterial({map:new THREE.CanvasTexture(badgeCanvas),transparent:true}),-.53,1.59,1.722,car);
const markers=[];objectives.forEach((o,i)=>{if(i===0)return;const group=new THREE.Group();group.position.set(trailX(o.at)+7,trailHeight(o.at),-o.at);scene.add(group);box(.15,4,.15,chrome,0,2,0,group);const sign=box(1.4,1.4,.15,o.water?mat('#74bdc8'):amber,0,4,0,group);sign.rotation.z=Math.PI/4; if(o.water){box(.8,1,.6,mat('#6fa6b4'),0,.5,0,group);}markers.push({group,index:i});});
const campZ=1480,camp=new THREE.Group();camp.position.set(trailX(campZ)+12,trailHeight(campZ),-campZ);scene.add(camp);const tent=mesh(new THREE.ConeGeometry(3.5,4,3),mat('#b97b3d'),0,2,0,camp);tent.rotation.y=Math.PI/6;box(1,.8,1,mat('#4c5142'),4,.4,0,camp);const fire=mesh(new THREE.ConeGeometry(.6,1.4,7),amber,4,.7,3,camp);const fireLight=new THREE.PointLight('#ffae42',15,14);fireLight.position.set(4,2,3);camp.add(fireLight);
const graphics=enhanceWorld(scene,car,ground,rockMats,renderer);
// Floating dust makes motion legible without hiding the trail.
const dustGeo=new THREE.BufferGeometry();const dustPositions=new Float32Array(180*3);dustGeo.setAttribute('position',new THREE.BufferAttribute(dustPositions,3));const dust=new THREE.Points(dustGeo,new THREE.PointsMaterial({color:'#d5ad76',size:.2,transparent:true,opacity:.35}));scene.add(dust);
let state=createState(),playing=false,paused=false,modalOpen=false,keys={},cruise=false,last=performance.now(),notificationTimer,viewAngle=0;
function resize(){renderer.setSize(innerWidth,innerHeight);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();}addEventListener('resize',resize);resize();
function notify(text){$('notification').textContent=text;$('notification').classList.add('visible');clearTimeout(notificationTimer);notificationTimer=setTimeout(()=>$('notification').classList.remove('visible'),3800);}
function openModal(title,content,action='BACK TO THE TRAIL →',callback=closeModal){keys={};cruise=false;$('auto-drive').textContent='DRIVE';$('auto-drive').setAttribute('aria-pressed','false');modalOpen=true;$('modal-title').textContent=title;$('modal-content').innerHTML=content;$('modal-action').textContent=action;$('modal-action').onclick=callback;$('modal').classList.remove('hidden');$('close-modal').focus();}
function closeModal(){if(paused){paused=false;$('pause').textContent='Ⅱ';}modalOpen=false;$('modal').classList.add('hidden');}
$('close-modal').onclick=closeModal;
function start(){state=createState();playing=true;paused=false;keys={};lastDone=0;failedShown=false;$('range').textContent='4H';$('lock').classList.remove('selected');$('pause').textContent='Ⅱ';closeModal();document.body.classList.add('playing');$('intro').classList.add('hidden');$('objectives').classList.remove('hidden');$('driving').classList.remove('hidden');cruise=false;$('auto-drive').textContent='DRIVE';$('auto-drive').setAttribute('aria-pressed','false');$('touch-controls').classList.remove('hidden');$('world').focus({preventScroll:true});notify('Welcome to Red Rock Run. Stay on the trail and watch for blue water markers.');}
$('start').onclick=start;
function doInteract(){if(!playing){notify('Start an expedition to explore the trail.');return;}const result=interact(state);notify(result.message);if(result.won)openModal('The best roads end here.',`<p>You reached the summit, gathered your water, and made camp. Take a breath. This view is yours.</p><div class="stat-grid"><div>DISTANCE<b>4.8 km</b></div><div>EXPEDITION TIME<b>${Math.floor(state.elapsed/60)}m ${Math.floor(state.elapsed%60)}s</b></div><div>FUEL REMAINING<b>${Math.round(state.fuel)}%</b></div><div>VEHICLE CONDITION<b>${Math.round(state.health)}%</b></div></div>`,'DRIVE AGAIN →',start);}
$('camp-button').onclick=doInteract;$('touch-interact').onclick=doInteract;
$('vehicle-button').onclick=()=>openModal('Toyota 4Runner',`<p>Your first adventure rig. A desert sand, fifth-generation TRD Off-Road with all-terrain tires, a roof rack, rear spare, and expedition supplies.</p><div class="stat-grid"><div>DRIVETRAIN<b>4WD</b></div><div>TRAIL RANGE<b>4H / 4L</b></div><div>DIFFERENTIAL<b>Rear locker</b></div><div>LOADOUT<b>Expedition ready</b></div></div>`);
$('gear-button').onclick=()=>openModal('Pack for the unexpected.',`<p>Your roof rack is loaded with a tent, recovery gear, and supplies. Collect the two blue water caches along the trail before making camp.</p><div class="stat-grid"><div>WATER<b>${Math.round(state.water)}%</b></div><div>COLLECTED CACHES<b>${state.completed.filter(i=>objectives[i].water).length} / 2</b></div><div>RECOVERY GEAR<b>Equipped</b></div><div>SHELTER<b>Roof rack tent</b></div></div>`);
const help=()=>openModal('Find your own pace.',`<p><b>W / ↑</b> Accelerate · <b>S / ↓</b> Reverse<br><b>A D / ← →</b> Steer · <b>Space</b> Brake<br><b>E</b> Collect water / set up camp<br><b>L</b> Toggle 4H / 4L · <b>F</b> Differential lock<br><b>Esc</b> Pause · <b>R</b> Restart</p><p>Stop within 32 meters of a blue marker to collect water. Stay on the tan trail to protect your suspension. Use 4L for slow off-road travel. Reach the summit and stop by the amber campsite marker to finish.</p>`);
$('help-button').onclick=help;
function togglePause(){if(modalOpen){closeModal();return;}if(!playing)return;paused=!paused;$('pause').textContent=paused?'▶':'Ⅱ';if(paused)openModal('Stay a little longer.', '<p>Your expedition is paused. The trail will be here when you’re ready.</p>','RESUME EXPEDITION →',()=>{paused=false;$('pause').textContent='Ⅱ';closeModal();});}
$('pause').onclick=togglePause;
function toggleRange(){state.low=!state.low;$('range').textContent=state.low?'4L':'4H';notify(state.low?'4L engaged. Slow, steady, and sure-footed.':'4H engaged. Ready for the open trail.');}
function toggleLock(){state.locked=!state.locked;$('lock').classList.toggle('selected',state.locked);notify(state.locked?'Rear differential locked. Extra traction off the trail.':'Differential unlocked.');}
$('range').onclick=toggleRange;$('lock').onclick=toggleLock;$('map-expand').onclick=()=>document.querySelector('.map-card').classList.toggle('expanded');
$('auto-drive').onclick=()=>{if(!playing||modalOpen||paused||state.failed||state.won)return;cruise=!cruise;$('auto-drive').textContent=cruise?'STOP':'DRIVE';$('auto-drive').setAttribute('aria-pressed',String(cruise));};
const codeAlias={KeyW:'w',KeyA:'a',KeyS:'s',KeyD:'d',Space:' ',ArrowUp:'w',ArrowDown:'s',ArrowLeft:'a',ArrowRight:'d'};
const alias={ArrowUp:'w',ArrowDown:'s',ArrowLeft:'a',ArrowRight:'d'};
addEventListener('keydown',e=>{const k=codeAlias[e.code]||alias[e.key]||e.key.toLowerCase();if(['w','a','s','d',' '].includes(k))e.preventDefault();if(['w','a','s','d',' '].includes(k)){keys[k]=true;if(k==='s'||k===' '){cruise=false;$('auto-drive').textContent='DRIVE';$('auto-drive').setAttribute('aria-pressed','false');}}if(e.repeat)return;if(k==='escape')togglePause();if(modalOpen)return;keys[k]=true;if(k==='e')doInteract();if(k==='l')toggleRange();if(k==='f')toggleLock();if(k==='r'&&playing)start();});addEventListener('keyup',e=>{keys[codeAlias[e.code]||alias[e.key]||e.key.toLowerCase()]=false;});function clearDriving(){keys={};cruise=false;$('auto-drive').textContent='DRIVE';$('auto-drive').setAttribute('aria-pressed','false');}addEventListener('blur',clearDriving);document.addEventListener('visibilitychange',clearDriving);
document.querySelectorAll('[data-key]').forEach(b=>{b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keys[b.dataset.key]=true;if(b.dataset.key==='s'||b.dataset.key===' '){cruise=false;$('auto-drive').textContent='DRIVE';$('auto-drive').setAttribute('aria-pressed','false');}});for(const event of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(event,()=>keys[b.dataset.key]=false);});
$('modal').addEventListener('keydown',e=>{if(e.key==='Tab'){const focusable=[$('close-modal'),$('modal-action')];e.preventDefault();(document.activeElement===focusable[0]?focusable[1]:focusable[0]).focus();}});
function drawMap(){const c=$('minimap').getContext('2d'),w=240,h=190;c.fillStyle='#26352c';c.fillRect(0,0,w,h);for(let i=0;i<15;i++){c.strokeStyle=i%2?'#59604a55':'#7e79533d';c.lineWidth=1;c.beginPath();for(let y=0;y<h;y+=3){const x=15+i*17+Math.sin(y/22+i)*13+Math.sin(y/50)*17;y===0?c.moveTo(x,y):c.lineTo(x,y);}c.stroke();}c.strokeStyle='#537d81';c.lineWidth=12;c.beginPath();for(let y=0;y<h;y++){const x=185+Math.sin(y/27)*11;y===0?c.moveTo(x,y):c.lineTo(x,y);}c.stroke();const mapX=z=>100+trailX(z)*.68,mapY=z=>170-z/TRAIL_LENGTH*147;c.strokeStyle='#ddb965';c.lineWidth=2;c.beginPath();for(let z=0;z<=1500;z+=10){z===0?c.moveTo(mapX(z),mapY(z)):c.lineTo(mapX(z),mapY(z));}c.stroke();objectives.forEach((o,i)=>{if(i===0)return;c.fillStyle=state.completed.includes(i)?'#7d9671':o.water?'#8bceda':'#eebf58';c.beginPath();c.arc(mapX(o.at),mapY(o.at),i===4?5:3,0,Math.PI*2);c.fill();});c.save();c.translate(mapX(state.z)+(state.x-trailX(state.z))*.68,mapY(state.z));c.fillStyle='#f5f3dc';c.strokeStyle='#14201c';c.lineWidth=2;c.beginPath();c.moveTo(0,-7);c.lineTo(5,5);c.lineTo(0,2);c.lineTo(-5,5);c.closePath();c.fill();c.stroke();c.restore();}
let lastDone=0,uiTick=0,failedShown=false;
function ui(){ $('speed').textContent=Math.round(Math.abs(state.speed)*2.237);for(const [key,id] of [['fuel','fuel'],['water','water'],['health','health']]){$(`${id}-bar`).style.width=state[key]+'%';$(`${id}-value`).textContent=Math.round(state[key])+'%';}$('distance').textContent=`${(state.z/TRAIL_LENGTH*4.8).toFixed(1)} / 4.8 KM`;$('trail-fill').style.width=state.z/TRAIL_LENGTH*100+'%';$('progress').textContent=`${state.completed.length} / 5`;$('mission-list').innerHTML=objectives.map((o,i)=>`<li class="${state.completed.includes(i)?'done':''}"><b>${state.completed.includes(i)?'✓':'◇'}</b>${o.name}</li>`).join('');if(state.completed.length>lastDone&&playing&&!state.won)notify('Trail milestone reached. Keep exploring.');lastDone=state.completed.length;markers.forEach(m=>m.group.visible=!state.completed.includes(m.index));drawMap();if(state.failed&&!failedShown){failedShown=true;openModal('Time for a fresh start.',`<p>${state.fuel<=0?'Your fuel tank is empty.':'Your vehicle needs repairs.'} Keep to the trail and drive gently on rough ground.</p>`,'RESTART EXPEDITION →',()=>{failedShown=false;start();});}}
const cameraTarget=new THREE.Vector3();
function frame(now){requestAnimationFrame(frame);const dt=Math.min((now-last)/1000,.25);last=now;if(playing&&!paused&&!modalOpen){const input={...keys,w:keys.w||cruise,brake:keys[' ']};updateFrame(state,input,dt);const near=objectives.find((o,i)=>(o.water||o.camp)&&!state.completed.includes(i)&&Math.abs(state.z-o.at)<32);$('map-label').textContent=near?'STOP + E TO INTERACT':'RED ROCK CANYON';}
const z=state.z,y=surfaceHeight(state.x,z);car.position.set(state.x,y+.05,-z);const dx=trailX(z+2)-trailX(z);const turn=(keys.d?1:0)-(keys.a?1:0);const desiredYaw=-Math.atan2(dx,2)-turn*.2;car.rotation.y=THREE.MathUtils.lerp(car.rotation.y,desiredYaw,.08);car.rotation.z=playing?Math.sin(z*1.7)*Math.min(Math.abs(state.speed)*.0018,.035):0;car.rotation.x=(surfaceHeight(state.x,z+1)-y)*.6;
if(playing){cameraTarget.set(state.x+4.8,y+4.1,-z+10);camera.position.lerp(cameraTarget,1-Math.exp(-dt*4));camera.lookAt(state.x-2,y+3.2,-z-22);}else{viewAngle+=dt*.015;camera.position.set(8+Math.sin(viewAngle)*1.5,y+5,14);camera.lookAt(-4,y+4,-28);}
graphics.update(z);sun.position.set(state.x-140,y+70,-z-220);sun.target.position.copy(car.position);
for(let i=0;i<180;i++){const age=((now*.0002+i/180)%1);dustPositions[i*3]=state.x+(Math.sin(i*19)*1.5)*(1+age*2);dustPositions[i*3+1]=y+age*1.8;dustPositions[i*3+2]=-z+2+age*(playing?Math.abs(state.speed)*.6:3);}dustGeo.attributes.position.needsUpdate=true;dust.material.opacity=playing?Math.min(.35,Math.abs(state.speed)*.015):.03;fire.scale.y=1+Math.sin(now*.008)*.15;
uiTick+=dt;if(uiTick>.15){ui();uiTick=0;}renderer.render(scene,camera);}
camera.position.set(9,7,11);ui();requestAnimationFrame(frame);
window.__overland={get state(){return state;},start,interact:doInteract,scene,renderer};
